trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macOS-latest'  # Utiliser macOS pour l'environnement de build Android

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g expo-cli
  displayName: 'Install Expo CLI'

- script: |
    cd frontend-expo
    npm install
  displayName: 'Install dependencies'

- script: |
    cd frontend-expo
    expo build:android --no-wait --release-channel production --type apk
  displayName: 'Build APK'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'frontend-expo/dist'
    artifactName: 'apk'
    publishLocation: 'pipeline'
  displayName: 'Publish APK'
